#This file contains the AWS CodePipeline configuration.

---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CodePipeline for deploying API to ECS Fargate"

Resources:
  MyPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: "arn:aws:iam::123456789012:role/service-role/AWS-CodePipeline-Service"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                RepositoryName: "my-api-repo"
                BranchName: "main"
              OutputArtifacts:
                - Name: "SourceOutput"
          ...
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: "CREATE_UPDATE"
                StackName: "my-api-stack"
                TemplatePath: "infra-output::infra.yaml"
                Capabilities: "CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM"
                RoleArn: "arn:aws:iam::123456789012:role/service-role/AWS-CodePipeline-Service"
              InputArtifacts:
                - Name: "SourceOutput"
              OutputArtifacts:
                - Name: "DeployOutput"
